### ISSUE TITLE
sharp error

### ISSUE THREAD

**Issue by Moritz3DMedien** [donmccurdy/glTF-Transform#1415]
**Describe the bug**
I get an Error with "Sharp" as I try to optimize a file

C:\Users\desig\Desktop>gltf-transform optimize Bruecke.glb Bruecke2.glb

error: Could not load the "sharp" module using the win32-x64 runtime
ERR_DLOPEN_FAILED: The specified procedure could not be found.
       \\?\C:\Users\desig\AppData\Roaming\npm\node_modules\@gltf-transform\cli\node_modules\@img\sharp-win32-x64\lib\sharp-win32-x64.node
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
- Using the canvas package on Windows?
    See https://sharp.pixelplumbing.com/install#canvas-and-windows
- Check for outdated versions of sharp in the dependency tree:
    npm ls sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install

There are two different versions. As the Error suggested I tried to install another sharp version, but didnt help I got just third version.

C:\Users\desig\Desktop>npm -g ls sharp
C:\Users\desig\AppData\Roaming\npm
`-- @gltf-transform/cli@4.0.0
  +-- @gltf-transform/functions@4.0.0
  | `-- ndarray-pixels@4.0.0
  |   `-- sharp@0.32.6
  `-- sharp@0.33.4

**Comment by donmccurdy** [comment]
Hi @Moritz3DMedien! I've just published a v4.0.1 release, with `ndarray-pixels` upgraded so that only the latest version of Sharp should be installed. Does that resolve the issue for you?

**Comment by Moritz3DMedien** [comment]
Yes! Works very well now. Thank you!

**Comment by FreakTheMighty** [comment]
@donmccurdy I'm still seeing the same error [4.0.2](https://www.npmjs.com/package/@gltf-transform/cli/v/4.0.2) within a `python:3.10` docker image.

> Error: Could not load the "sharp" module using the linux-x64 runtime

Downgrading to gltf-transform@3.10.1 resolves the problem for me.

**Comment by donmccurdy** [comment]
@FreakTheMighty there's a lot of troubleshooting help in https://sharp.pixelplumbing.com/install#cross-platform, have you gone through that?

**Comment by FreakTheMighty** [comment]
I haven’t gone through that, let me take a look. I have tried to follow some of the hints provided with the error, but without success.

I am installing the cli globally.

**Comment by zeux** [comment]
fwiw I had the exact same issue on Linux (latest Ubuntu, stock node/npm installed through apt). None of the sharp troubleshooting steps helped, but what did help is setting npm install prefix to "/home/user/.local" instead of the default system-level installation. I'm not sure what the root cause is.

**Comment by donmccurdy** [comment]
> latest Ubuntu, stock node/npm installed through apt...

Do you know which `node` and `npm` versions came stock? Hm, not sure what to make of the install prefix change fixing it.

**Comment by zeux** [comment]
```
$ node -v
v18.19.1
$ npm -v
10.8.1
```

I'm not sure why the prefix change changes anything here, but maybe this is related to the need to use sudo to do global npm install by default (as the default location is not user writeable), and sharp installation somehow not working properly under root?

**Comment by zeux** [comment]
For posterity, I reproduced this again and attaching full log:

```sh
$ npm -g install @gltf-transform/cli
npm error code EACCES
npm error syscall mkdir
npm error path /usr/local/lib/node_modules/@gltf-transform/cli
npm error errno -13
npm error [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@gltf-transform/cli'] {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'mkdir',
npm error   path: '/usr/local/lib/node_modules/@gltf-transform/cli'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as the current user
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.
npm error A complete log of this run can be found in: /home/zeux/.npm/_logs/2024-07-23T01_44_13_324Z-debug-0.log
$ sudo npm -g install @gltf-transform/cli
[sudo] password for zeux: 
npm WARN deprecated @types/wrap-ansi@8.1.0: This is a stub types definition. wrap-ansi provides its own type definitions, so you do not need this installed.

added 234 packages in 4s

52 packages are looking for funding
  run `npm fund` for details
$ gltf-transform optimize test/scene.gltf test.glb
/usr/local/lib/node_modules/@gltf-transform/cli/node_modules/sharp/lib/sharp.js:114
  throw new Error(help.join('\n'));
        ^

Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/local/lib/node_modules/@gltf-transform/cli/node_modules/sharp/lib/sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@gltf-transform/cli/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

Node.js v18.19.1
```
