### ISSUE TITLE
weld() causes some meshes to have missing faces

### ISSUE THREAD

**Issue by harrycollin** [donmccurdy/glTF-Transform#870]
I've noticed some missing faces when using the weld function. The tolerance has been set really low to minimise errors but doesn't seem to help. There is an attachment zip with both models. 

With weld + dedup
![image](https://user-images.githubusercontent.com/10602138/226967077-d70516cc-752f-4e4a-aa1c-227cbf5d2f72.png)

Without weld + dedup
![image](https://user-images.githubusercontent.com/10602138/226967484-88a7ffb4-a8a4-4781-8795-3331b719355d.png)

[models.zip](https://github.com/donmccurdy/glTF-Transform/files/11042198/models.zip)

**Comment by donmccurdy** [comment]
Thanks @harrycollin! It looks like #803 should fix the issue once it is published.

**Comment by harrycollin** [comment]
Hello @donmccurdy, 
Thank you for that update. It did in-fact solve a lot of the problems I was seeing in the first implementation of weld(). It seems that some meshes still don't behave well in the latest release. Unfortunately I'm not able to share more details about the models on here other than what I've attached. I can provide more info, but it would have to be sent to you privately. What do you think could be the problem with these? 

Thanks!

Not Welded
![image](https://user-images.githubusercontent.com/10602138/228312095-2d733ceb-1379-4aa5-b61e-b2967f3fd64e.png)


Welded
![image](https://user-images.githubusercontent.com/10602138/228311988-03fa010c-9f81-463d-94f3-5062a24f38aa.png)
[outputs.zip](https://github.com/donmccurdy/glTF-Transform/files/11092276/outputs.zip)

**Comment by donmccurdy** [comment]
I expect weld() and weldPrimitive() would do the same thing given those options. The "optimize" command does a lot more, including joining meshes before welding — so that nearby meshes could be welded into one another. There is a `--no-join` option to prevent that on the optimize command if needed.

**Comment by harrycollin** [comment]
For context I'm only using dedup and weld in Javascript - not using the CLI. It's interesting though that weld and weld primitive are producing different results. Either way thank you for investigating :)

**Comment by donmccurdy** [comment]
Hm, you can see how `weld()` is implemented here —

https://github.com/donmccurdy/glTF-Transform/blob/2af635f363d8ca2c1b1665199b8836899a23f9c8/packages/functions/src/weld.ts#L103-L114

For the same options it should give the same result. 😕

**Comment by harrycollin** [comment]
That's strange. I'll double check the results tomorrow and post back.

**Comment by donmccurdy** [comment]
@harrycollin I'm also seeing that running welds with the 'exhaustive' option enabled can cause some issues, see #886 + #887. It shouldn't make a difference in visual quality, but for some reason it does, so I've turned that option off by default in the latest release.

**Comment by harrycollin** [comment]
I'll keep testing with more models and report anything weird.
